debug: false
reload_timer: 10
policies:
  - id: 0
    src_cidr:  'ALL'
    path_re_match: '^/get/.*$'
    method: GET
    headers: []
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        repeat: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"local_get_default"}'
        direct_response_body_encoding: NONE
  - id: 1
    src_cidr:  'ALL'
    path_re_match: '^\/post\/.*$'
    method: POST
    headers: []
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        repeat: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"post","config":"local_post_default"}'
        direct_response_body_encoding: NONE
  - id: 2
    src_cidr:  'ALL'
    path_re_match: '^\/put\/.*$'
    method: PUT
    headers: []
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        repeat: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"put","config":"local_put_default"}'
        direct_response_body_encoding: NONE
  - id: 3
    src_cidr:  'ALL'
    path_re_match: '^\/patch\/.*$'
    method: PATCH
    headers: []
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        repeat: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"patch","config":"local_patch_default"}'
        direct_response_body_encoding: NONE
  - id: 4
    src_cidr:  'ALL'
    path_re_match: '^\/head\/.*$'
    method: HEAD
    headers: []
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        repeat: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"head","config":"local_head_default"}'
        direct_response_body_encoding: NONE
  - id: 5
    src_cidr:  'ALL'
    path_re_match: '^\/delete\/.*$'
    method: DELETE
    headers: []
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        repeat: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"delete","config":"local_delete_default"}'
        direct_response_body_encoding: NONE
  - id: 6
    src_cidr:  'ALL'
    path_re_match: 'ALL'
    method: GET
    headers: []
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        repeat: 5
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"local_all_default_ok"}'
        direct_response_body_encoding: NONE
      - delay_ms: 2000
        repeat: 1
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"local_default_error"}'
        direct_response_body_encoding: NONE
