debug: true
reload_timer: 10
policies:
  - id: 0
    ip_version: 4
    src_cidr:  'ALL'
    day_of_week: SUMTWRFSA
    start_time: '00:00:00'
    stop_time: '23:59:59'
    env: []
    method: GET
    headers: []
    path_re_match: 'ALL'
    query: []
    reply_scripts:
      - delay_ms: 0
        repeat: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"local_get_default"}'
        direct_response_body_encoding: NONE
  - id: 1
    ip_version: 4
    src_cidr:  'ALL'
    day_of_week: SUMTWRFSA
    start_time: '00:00:00'
    stop_time: '23:59:59'
    env: []
    method: POST
    headers: []
    path_re_match: 'ALL'
    query: []
    reply_scripts:
      - delay_ms: 0
        repeat: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"post","config":"local_post_default"}'
        direct_response_body_encoding: NONE
  - id: 2
    ip_version: 4
    src_cidr:  'ALL'
    day_of_week: SUMTWRFSA
    start_time: '00:00:00'
    stop_time: '23:59:59'
    env: []
    method: PUT
    headers: []
    path_re_match: 'ALL'
    query: []
    reply_scripts:
      - delay_ms: 0
        repeat: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"put","config":"local_put_default"}'
        direct_response_body_encoding: NONE
  - id: 3
    ip_version: 4
    src_cidr:  'ALL'
    day_of_week: SUMTWRFSA
    start_time: '00:00:00'
    stop_time: '23:59:59'
    env: []
    method: PATCH
    headers: []
    path_re_match: 'ALL'
    query: []
    reply_scripts:
      - delay_ms: 0
        repeat: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"patch","config":"local_patch_default"}'
        direct_response_body_encoding: NONE
  - id: 4
    ip_version: 4
    src_cidr:  'ALL'
    day_of_week: SUMTWRFSA
    start_time: '00:00:00'
    stop_time: '23:59:59'
    env: []
    method: HEAD
    headers: []
    path_re_match: 'ALL'
    query: []
    reply_scripts:
      - delay_ms: 0
        repeat: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"head","config":"local_head_default"}'
        direct_response_body_encoding: NONE
  - id: 5
    ip_version: 4
    src_cidr:  'ALL'
    day_of_week: SUMTWRFSA
    start_time: '00:00:00'
    stop_time: '23:59:59'
    env: []
    method: DELETE
    headers: []
    path_re_match: 'ALL'
    query: []
    reply_scripts:
      - delay_ms: 0
        repeat: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"delete","config":"local_delete_default"}'
        direct_response_body_encoding: NONE
  - id: 6
    ip_version: 4
    src_cidr:  'ALL'
    day_of_week: SUMTWRFSA
    start_time: '00:00:00'
    stop_time: '23:59:59'
    env: []
    method: GET
    headers: []
    path_re_match: 'ALL'
    query:
      - fail: 'ANY'
    reply_scripts:
      - delay_ms: 0
        repeat: 1
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"local_all_default_ok"}'
        direct_response_body_encoding: NONE
      - delay_ms: 2000
        repeat: 1
        action: direct_response
        direct_response_status_code: 500
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"local_default_error"}'
        direct_response_body_encoding: NONE
  - id: 7
    ip_version: 4
    src_cidr:  'ALL'
    day_of_week: SUMTWRFSA
    start_time: '00:00:00'
    stop_time: '23:59:59'
    env: []
    method: GET
    headers: []
    path_re_match: '^/proxy/.*$'
    query: []
    reply_scripts:
      - delay_ms: 0
        repeat: 0
        action: proxy
        proxy_url: 'https://raw.githubusercontent.com/jgruberf5/ViaUATEndpoint/main/configs.yaml'
