debug: false
policies:
  - id: 0
    src_cidr:  'ALL'
    path_re_match: 'ANY'
    method: GET
    headers:
      - x-volterra-location: ams9-ams
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        repeat: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"amsterdam_get"}'
        direct_response_body_encoding: NONE
  - id: 1
    src_cidr:  'ALL'
    path_re_match: 'ANY'
    method: POST
    headers:
      - x-volterra-location: ams9-ams
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        repeat: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"amsterdam_post"}'
        direct_response_body_encoding: NONE
  - id: 2
    src_cidr:  'ALL'
    path_re_match: 'ANY'
    method: PUT
    headers:
      - x-volterra-location: ams9-ams
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        repeat: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"amsterdam_put"}'
        direct_response_body_encoding: NONE
  - id: 3
    src_cidr:  'ALL'
    path_re_match: 'ANY'
    method: PATCH
    headers:
      - x-volterra-location: ams9-ams
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        repeat: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"amsterdam_patch"}'
        direct_response_body_encoding: NONE
  - id: 4
    src_cidr:  'ALL'
    path_re_match: 'ANY'
    method: HEAD
    headers:
      - x-volterra-location: ams9-ams
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        repeat: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"amsterdam_head"}'
        direct_response_body_encoding: NONE
  - id: 5
    src_cidr:  'ALL'
    path_re_match: 'ANY'
    method: DELETE
    headers:
      - x-volterra-location: ams9-ams
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        repeat: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"amsterdam_delete"}'
        direct_response_body_encoding: NONE
  - id: 6
    src_cidr:  'ALL'
    path_re_match: 'ALL'
    method: ANY
    headers:
      - x-volterra-location: ams9-ams
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"amsterdam_generic"}'
        direct_response_body_encoding: NONE
  - id: 7
    src_cidr:  '18.0.0.0/8'
    path_re_match: 'ALL'
    method: GET
    headers:
      - x-volterra-location: ams9-ams
    ip_version: 4
    reply_scripts:
      - delay_ms: 5000
        repeat: 0
        action: direct_response
        direct_response_status_code: 500
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"fail"}'
        direct_response_body_encoding: NONE
  - id: 8
    src_cidr: '174.197.66.183/32'
    path_re_match: 'ALL'
    method: GET
    headers:
      - x-volterra-location: ams9-ams
    ip_version: 4
    reply_scripts:
      - delay_ms: 5000
        repeat: 0
        action: direct_response
        direct_response_status_code: 500
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"fail"}'
        direct_response_body_encoding: NONE
