debug: false
policies:
  - id: 0
    src_cidr:  'ALL'
    path_re_match: '^/get/.*$'
    method: GET
    header: NONE
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        status_code: 200
        mime_type: 'application/json'
        repeat: 0
        body: '{"method":"get","config":"frankfurt_get_default"}'
        body_encoding: NONE
  - id: 1
    src_cidr:  'ALL'
    path_re_match: '^\/post\/.*$'
    method: POST
    header: NONE
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        status_code: 200
        mime_type: 'application/json'
        repeat: 0
        body: '{"method":"post","config":"frankfurt_post_default"}'
        body_encoding: NONE
  - id: 2
    src_cidr:  'ALL'
    path_re_match: '^\/put\/.*$'
    method: PUT
    header: NONE
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        status_code: 200
        mime_type: 'application/json'
        repeat: 0
        body: '{"method":"put","config":"frankfurt_put_default"}'
        body_encoding: NONE
  - id: 3
    src_cidr:  'ALL'
    path_re_match: '^\/patch\/.*$'
    method: PATCH
    header: NONE
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        status_code: 200
        mime_type: 'application/json'
        repeat: 0
        body: '{"method":"patch","config":"frankfurt_patch_default"}'
        body_encoding: NONE
  - id: 4
    src_cidr:  'ALL'
    path_re_match: '^\/head\/.*$'
    method: HEAD
    header: NONE
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        status_code: 200
        mime_type: 'application/json'
        repeat: 0
        body: '{"method":"head","config":"frankfurt_head_default"}'
        body_encoding: NONE
  - id: 5
    src_cidr:  'ALL'
    path_re_match: '^\/delete\/.*$'
    method: DELETE
    header: NONE
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        status_code: 200
        mime_type: 'application/json'
        repeat: 0
        body: '{"method":"delete","config":"frankfurt_delete_default"}'
        body_encoding: NONE
  - id: 6
    src_cidr:  'ALL'
    path_re_match: 'ALL'
    method: GET
    header: NONE
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        status_code: 200
        mime_type: 'application/json'
        repeat: 5
        body: '{"method":"get","config":"frankfurt_all_default_ok"}'
        body_encoding: NONE
      - delay_ms: 2000
        status_code: 500
        mime_type: 'application/json'
        repeat: 1
        body: '{"method":"get","config":"frankfurt_default_error"}'
        body_encoding: NONE
