debug: false
reload_timer: 60
policies:
  - id: 0
    src_cidr:  'ALL'
    path_re_match: 'ANY'
    method: ANY
    headers:
      - x-volterra-location: ams9-ams
    header_policy_match: AND
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        repeat: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"amsterdam_service"}'
        direct_response_body_encoding: NONE
  - id: 1
    src_cidr:  'ALL'
    path_re_match: 'ALL'
    method: ANY
    headers:
      - x-volterra-location: dc12-ash
    header_policy_match: AND
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"ashburn_service"}'
        direct_response_body_encoding: NONE
  - id: 2
    src_cidr:  'ALL'
    path_re_match: 'ALL'
    method: ANY
    headers:
      - x-volterra-location: dal3-dal
    header_policy_match: AND
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"dallas_service"}'
        direct_response_body_encoding: NONE
  - id: 3
    src_cidr:  'ALL'
    path_re_match: 'ALL'
    method: ANY
    headers:
      - x-volterra-location: fr4-fra
    header_policy_match: AND
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"frankfurt_service"}'
        direct_response_body_encoding: NONE
  - id: 4
    src_cidr:  'ALL'
    path_re_match: 'ALL'
    method: ANY
    headers:
      - x-volterra-location: hk2-hkg
    header_policy_match: AND
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"hongkong_service"}'
        direct_response_body_encoding: NONE
  - id: 5
    src_cidr:  'ALL'
    path_re_match: 'ALL'
    method: ANY
    headers:
      - x-volterra-location: ls1-lis
    header_policy_match: AND
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"lisabon_service"}'
        direct_response_body_encoding: NONE
  - id: 6
    src_cidr:  'ALL'
    path_re_match: 'ALL'
    method: ANY
    headers:
      - x-volterra-location: tn2-lon
    header_policy_match: AND
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"london_service"}'
        direct_response_body_encoding: NONE
  - id: 7
    src_cidr:  'ALL'
    path_re_match: 'ALL'
    method: ANY
    headers:
      - x-volterra-location: me1-mel
    header_policy_match: AND
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"melbourne_service"}'
        direct_response_body_encoding: NONE
  - id: 8
    src_cidr:  'ALL'
    path_re_match: 'ALL'
    method: ANY
    headers:
      - x-volterra-location: ny8-nyc
    header_policy_match: AND
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"newyork_service"}'
        direct_response_body_encoding: NONE
  - id: 9
    src_cidr:  'ALL'
    path_re_match: 'ALL'
    method: ANY
    headers:
      - x-volterra-location: os1-osa
    header_policy_match: AND
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"osaka_service"}'
        direct_response_body_encoding: NONE
  - id: 10
    src_cidr:  'ALL'
    path_re_match: 'ALL'
    method: ANY
    headers:
      - x-volterra-location: pa2-par
    header_policy_match: AND
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"paris_service"}'
        direct_response_body_encoding: NONE
  - id: 11
    src_cidr:  'ALL'
    path_re_match: 'ALL'
    method: ANY
    headers:
      - x-volterra-location: sv10-sjc
    header_policy_match: AND
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"sanjose_service"}'
        direct_response_body_encoding: NONE
  - id: 12
    src_cidr:  'ALL'
    path_re_match: 'ALL'
    method: ANY
    headers:
      - x-volterra-location: wes-sea
    header_policy_match: AND
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"seattle_service"}'
        direct_response_body_encoding: NONE
  - id: 13
    src_cidr:  'ALL'
    path_re_match: 'ALL'
    method: ANY
    headers:
      - x-volterra-location: sg3-sin
    header_policy_match: AND
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"singapore_service}'
        direct_response_body_encoding: NONE
  - id: 14
    src_cidr:  'ALL'
    path_re_match: 'ALL'
    method: ANY
    headers:
      - x-volterra-location: sto6-sto
    header_policy_match: AND
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"stockholm_service"}'
        direct_response_body_encoding: NONE
  - id: 15
    src_cidr:  'ALL'
    path_re_match: 'ALL'
    method: ANY
    headers:
      - x-volterra-location: sy5-syd
    header_policy_match: AND
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"sydney_service"}'
        direct_response_body_encoding: NONE
  - id: 16
    src_cidr:  'ALL'
    path_re_match: 'ALL'
    method: ANY
    headers:
      - x-volterra-location: ty8-tky
    header_policy_match: AND
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"tokyo_service"}'
        direct_response_body_encoding: NONE
  - id: 17
    src_cidr:  'ALL'
    path_re_match: 'ALL'
    method: ANY
    headers:
      - x-volterra-location: tr2-tor
    header_policy_match: AND
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"toronto_service"}'
        direct_response_body_encoding: NONE
  - id: 18
    src_cidr:  'ALL'
    path_re_match: 'ALL'
    method: ANY
    headers:
      - x-volterra-location: pa4-par
    header_policy_match: AND
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"paris_service"}'
        direct_response_body_encoding: NONE
  - id: 19
    src_cidr:  'ALL'
    path_re_match: 'ALL'
    method: ANY
    headers: []
    header_policy_match: AND
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"global_generic_service"}'
        direct_response_body_encoding: NONE
