debug: false
policies:
  - id: 0
    src_cidr:  'ALL'
    path_re_match: 'ANY'
    method: GET
    headers:
      - x-volterra-location: wes-sea
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        repeat: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"seattle_get"}'
        direct_response_body_encoding: NONE
  - id: 1
    src_cidr:  'ALL'
    path_re_match: 'ANY'
    method: POST
    headers:
      - x-volterra-location: wes-sea
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        repeat: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"seattle_post"}'
        direct_response_body_encoding: NONE
  - id: 2
    src_cidr:  'ALL'
    path_re_match: 'ANY'
    method: PUT
    headers:
      - x-volterra-location: wes-sea
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        repeat: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"seattle_put"}'
        direct_response_body_encoding: NONE
  - id: 3
    src_cidr:  'ALL'
    path_re_match: 'ANY'
    method: PATCH
    headers:
      - x-volterra-location: wes-sea
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        repeat: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"seattle_patch"}'
        direct_response_body_encoding: NONE
  - id: 4
    src_cidr:  'ALL'
    path_re_match: 'ANY'
    method: HEAD
    headers:
      - x-volterra-location: wes-sea
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        repeat: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"seattle_head"}'
        direct_response_body_encoding: NONE
  - id: 5
    src_cidr:  'ALL'
    path_re_match: 'ANY'
    method: DELETE
    headers:
      - x-volterra-location: wes-sea
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        repeat: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"seattle_delete"}'
        direct_response_body_encoding: NONE
  - id: 6
    src_cidr:  'ALL'
    path_re_match: 'ALL'
    method: ANY
    headers:
      - x-volterra-location: wes-sea
    ip_version: 4
    reply_scripts:
      - delay_ms: 0
        action: direct_response
        direct_response_status_code: 200
        direct_response_mime_type: 'application/json'
        direct_response_body: '{"method":"get","config":"seattle_generic"}'
        direct_response_body_encoding: NONE
